# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  # Update Python deps for the template (not the generated project)
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "project infrastructure"

  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "project infrastructure"

  # Update npm packages
  - package-ecosystem: "npm"
    directory: "{{cookiecutter.project_slug}}/"
    schedule:
      interval: "daily"
    labels:
      - "update"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "{{cookiecutter.project_slug}}/compose/local/django/"
      - "{{cookiecutter.project_slug}}/compose/local/docs/"
      - "{{cookiecutter.project_slug}}/compose/production/django/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "update"
    groups:
      docker-python:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "{{cookiecutter.project_slug}}/compose/local/node/"
      - "{{cookiecutter.project_slug}}/compose/production/aws/"
      - "{{cookiecutter.project_slug}}/compose/production/postgres/"
      - "{{cookiecutter.project_slug}}/compose/production/nginx/"
      - "{{cookiecutter.project_slug}}/compose/production/traefik/"
    schedule:
      interval: "daily"
    labels:
      - "update"
