volumes:
  {{ cookiecutter.project_slug }}_local_postgres_data: {}
  {{ cookiecutter.project_slug }}_local_postgres_data_backups: {}
  {% if cookiecutter.use_celery == 'y' %}{{ cookiecutter.project_slug }}_local_redis_data: {}{% endif %}
  {% if cookiecutter.use_rq == 'y' %}{{ cookiecutter.project_slug }}_local_valkey_data: {}{% endif %}

services:
  django:{% if cookiecutter.use_celery == 'y' or cookiecutter.use_rq == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    container_name: {{ cookiecutter.project_slug }}_local_django
    depends_on:
      - postgres
      {%- if cookiecutter.use_celery == 'y' %}
      - redis
      {%- endif %}
      {%- if cookiecutter.use_rq == 'y' %}
      - valkey
      {%- endif %}
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    container_name: {{ cookiecutter.project_slug }}_local_postgres
    volumes:
      {%- if cookiecutter.postgresql_version|int >= 18 %}
      - {{ cookiecutter.project_slug }}_local_postgres_data:/var/lib/postgresql/{{ cookiecutter.postgresql_version }}/docker
      {%- else %}
      - {{ cookiecutter.project_slug }}_local_postgres_data:/var/lib/postgresql/data
      {%- endif %}
      - {{ cookiecutter.project_slug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  {%- if cookiecutter.use_mailpit == 'y' %}

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: {{ cookiecutter.project_slug }}_local_mailpit
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if cookiecutter.use_celery == 'y' %}

  redis:
    image: docker.io/redis:7.2
    container_name: {{ cookiecutter.project_slug }}_local_redis
    volumes:
      - {{ cookiecutter.project_slug }}_local_redis_data:/data

  {%- endif %}
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celeryworker
    container_name: {{ cookiecutter.project_slug }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_celerybeat
    container_name: {{ cookiecutter.project_slug }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_flower
    container_name: {{ cookiecutter.project_slug }}_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  {%- endif %}
  {%- if cookiecutter.use_rq == 'y' %}

  valkey:
    image: docker.io/valkey/valkey:8.0
    container_name: {{ cookiecutter.project_slug }}_local_valkey
    volumes:
      - {{ cookiecutter.project_slug }}_local_valkey_data:/data

  rqworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_rqworker
    container_name: {{ cookiecutter.project_slug }}_local_rqworker
    depends_on:
      - valkey
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-rqworker

  rqscheduler:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_rqscheduler
    container_name: {{ cookiecutter.project_slug }}_local_rqscheduler
    depends_on:
      - valkey
      - postgres
      {%- if cookiecutter.use_mailpit == 'y' %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-rqscheduler

  rqdashboard:
    <<: *django
    image: {{ cookiecutter.project_slug }}_local_rqdashboard
    container_name: {{ cookiecutter.project_slug }}_local_rqdashboard
    ports:
      - '9181:9181'
    command: /start-rqdashboard

  {%- endif %}
  {%- if cookiecutter.frontend_pipeline in ['Gulp', 'Webpack'] %}

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_node
    container_name: {{ cookiecutter.project_slug }}_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      {%- if cookiecutter.frontend_pipeline == 'Gulp' %}
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
      {%- endif %}

  {%- endif %}
