services:
  - docker

language: python

python: 3.8

before_install:
  - docker-compose -v
  - docker -v

matrix:
  include:
    - name: Test results
      script: tox -e py38
    - name: Black template
      script: tox -e black-template
    - name: Basic Docker
      script: sh tests/test_docker.sh
    - name: Extended Docker
      script: sh tests/test_docker.sh use_celery=y use_drf=y js_task_runner=Gulp
    - name: Bare metal
      script: sh tests/test_bare.sh use_celery=y use_compressor=y
      services:
        - postgresql
        - redis-server
      env:
        - CELERY_BROKER_URL=redis://localhost:6379/0

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
