dist: xenial

services:
  - docker

language: python

python: 3.6

before_install:
  - docker-compose -v
  - docker -v

matrix:
  include:
    - name: Test results
      script: tox -e py36
    - name: Run flake8 on result
      script: tox -e flake8
    - name: Run black on result
      script: tox -e black
    - name: Black template
      script: tox -e black-template
    - name: Basic Docker
      script: sh tests/test_docker.sh
    - name: Docker with Celery
      script: sh tests/test_docker.sh use_celery=y

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
