name: Update Changelog

on:
  # Every day at 2am
  schedule:
    - cron: "0 2 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  update:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'cookiecutter'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set git details
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
      - name: Update changelog
        run: uv run --frozen scripts/update_changelog.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
